### PR TITLE
Project create view fixes

### LINKED ISSUE #178: Empty list item in errors when validating project form
https://github.com/ProyectoIntegrador2018/BlueMarket/blob/6751a20fae9bb4ac8c6187f7acfd9a87a77114fc/resources/views/projects/create.blade.php#L217

This change causes the following issue:

image

### PR DESCRIPTION
**Pull request by katiearriagam**
## Changes
- Show separate errors in front-end when both the new team field and the existing team field are empty. 
- Handle the case when the user leaves an empty photo in the project. 

## Fixes
#178

### CODE REVIEW

File: app/Http/Controllers/ProjectController.php [hunk 1]
```diff
@@ -119,7 +119,6 @@ private function validateTeam($team_id, $course_id) {
 
 	private function saveRecord(array $attributes) {
 		$path = isset($attributes['projectImage']) ? Storage::putFile('public', $attributes['projectImage']) : null;
-		$path = $path != null ? Storage::url($path) : null;
```
Comment (hecerinc) [inline app/Http/Controllers/ProjectController.php]: Por qu&eacute; borraste esto?
